Repository Matroska-Org/libebml, pull requests merged in 2021-02, with the labels that each got.

#76 Fix misc reading overflows
  src/EbmlBinary.cpp
  src/EbmlCrc32.cpp
  src/EbmlDate.cpp
  src/EbmlFloat.cpp
  src/EbmlSInteger.cpp
  src/EbmlString.cpp
  src/EbmlUInteger.cpp
  src/EbmlUnicodeString.cpp
Labels: bug

#77 Fix EbmlBinary using unallocated pointer or leaking allocated buffers
  src/EbmlBinary.cpp
Labels: bug

#68 replace crc32 macros with constexpr function
  src/EbmlCrc32.cpp
Labels: enhancement

#79 remove coremake project files
  ChangeLog
  libebml.proj
Labels: build-system
