Repository Matroska-Org/libebml, pull requests merged in 2022-10, with the labels that each got.

#82 clang-tidy fixes
  ebml/Debug.h
  ebml/EbmlCrc32.h
  ebml/EbmlDate.h
  ebml/EbmlElement.h
  ebml/EbmlMaster.h
  ebml/EbmlSInteger.h
  ebml/EbmlString.h
  ebml/EbmlUInteger.h
  ebml/EbmlUnicodeString.h
  ebml/MemIOCallback.h
  ebml/MemReadIOCallback.h
  ebml/SafeReadIOCallback.h
  ebml/StdIOCallback.h
  src/EbmlContexts.cpp
  src/EbmlCrc32.cpp
  src/EbmlDate.cpp
  src/EbmlElement.cpp
  src/EbmlFloat.cpp
  src/EbmlMaster.cpp
  src/EbmlSInteger.cpp
  src/EbmlUInteger.cpp
  src/EbmlUnicodeString.cpp
  src/EbmlVoid.cpp
  src/MemIOCallback.cpp
  src/MemReadIOCallback.cpp
  src/SafeReadIOCallback.cpp
  src/StdIOCallback.cpp
Labels: api-break, abi-break

#105 bump soname to 6 due to ABI-breaking changes & bump version number
  CMakeLists.txt
  NEWS.md
  ebml/EbmlVersion.h
  src/EbmlVersion.cpp
Labels: abi-break

#110 Use C++ Numeric limits where possible
  src/StdIOCallback.cpp
Labels: enhancement

#88 add defaulted operator= constructor
  ebml/EbmlBinary.h
  src/EbmlBinary.cpp
Labels: bug

#118 [1.x] do 1.x build actions when pushing to the v1.x branch
  .github/workflows/linux-gcc10.yaml
  .github/workflows/linux.yaml
  .github/workflows/macos.yaml
  .github/workflows/windows.yaml
Labels: build-system

#119 Draft: 1x abi break test
  .github/workflows/abibreak.yaml
Labels: abi-break, build-system

#128 remove confusing SVN version tag
  ebml/EbmlBinary.h
  ebml/EbmlConfig.h
  ebml/EbmlElement.h
  ebml/EbmlEndian.h
  ebml/EbmlTypes.h
  ebml/StdIOCallback.h
  src/EbmlBinary.cpp
  src/EbmlCrc32.cpp
  src/EbmlDate.cpp
  src/EbmlUnicodeString.cpp
  src/IOCallback.cpp
  src/StdIOCallback.cpp
Labels: enhancement

#129 Use proper integer literal and remove EBML_PRETTYLONGINT
  ebml/EbmlConfig.h
  src/EbmlUInteger.cpp
Labels: abi-break

#130 remove unused utf types
  ebml/EbmlTypes.h
Labels: api-break

#127 Misc endian cleanup
  CMakeLists.txt
  ebml/EbmlConfig.h
  ebml/EbmlEndian.h
  ebml/EbmlTypes.h
  src/EbmlCrc32.cpp
Labels: api-break, abi-break

#132 Add a simpler/faster Endian API for 16/32/64 Big-Endian buffers
  ebml/EbmlEndian.h
  src/EbmlDate.cpp
  src/EbmlFloat.cpp
  src/IOCallback.cpp
  src/MemReadIOCallback.cpp
  src/SafeReadIOCallback.cpp
Labels: enhancement

#134 Set all public compile definitions in the pkg-config file
  CMakeLists.txt
  libebml.pc.in
Labels: build-system
