Repository Matroska-Org/libebml, pull requests merged in 2022-05, with the labels that each got.

#95 CMakeLists: update to c++14
  CMakeLists.txt
Labels: build-system

#98 keep the path for pkg-config path if they are absolute
  CMakeLists.txt
Labels: bug, build-system

#94 initialize UnixEpochDelay in declaration
  ebml/EbmlDate.h
  src/EbmlDate.cpp
Labels: enhancement
