Repository Matroska-Org/libebml, pull requests merged in 2024-01, with the labels that each got.

#200 Use templates to factorize generic code
  ebml/EbmlDate.h
  ebml/EbmlElement.h
  ebml/EbmlFloat.h
  ebml/EbmlSInteger.h
  ebml/EbmlString.h
  ebml/EbmlUInteger.h
  ebml/EbmlUnicodeString.h
  src/EbmlDate.cpp
  src/EbmlFloat.cpp
  src/EbmlSInteger.cpp
  src/EbmlString.cpp
  src/EbmlUInteger.cpp
  src/EbmlUnicodeString.cpp
Labels: api-break, abi-break

#206 add a test to write/read an EBML header
  CMakeLists.txt
  test/test_header.cxx
Labels: build-system

#205 Move some common virtual methods in EbmlElement
  ebml/EbmlDummy.h
  ebml/EbmlElement.h
  src/EbmlDummy.cpp
Labels: api-break, abi-break

#210 factorize the calls to the write filter per element
  ebml/EbmlElement.h
  src/EbmlElement.cpp
  src/EbmlFloat.cpp
  src/EbmlMaster.cpp
  src/EbmlSInteger.cpp
  src/EbmlString.cpp
  src/EbmlUInteger.cpp
  src/EbmlUnicodeString.cpp
Labels: api-break, abi-break

#213 Create less bogus elements on reading
  ebml/EbmlElement.h
  src/EbmlElement.cpp
Labels: enhancement

#215 implement EbmlMaster::ReadData
  src/EbmlMaster.cpp
Labels: enhancement

#218 Pass the size to check on an element
  ebml/EbmlBinary.h
  ebml/EbmlDate.h
  ebml/EbmlElement.h
  ebml/EbmlFloat.h
  ebml/EbmlMaster.h
  ebml/EbmlSInteger.h
  ebml/EbmlString.h
  ebml/EbmlUInteger.h
  ebml/EbmlUnicodeString.h
  src/EbmlElement.cpp
Labels: api-break, abi-break

#207 [RFC] keep track of minver and maxver per element
  ebml/EbmlElement.h
  src/EbmlBinary.cpp
  src/EbmlCrc32.cpp
  src/EbmlDummy.cpp
  src/EbmlHead.cpp
  src/EbmlMaster.cpp
  src/EbmlSInteger.cpp
  src/EbmlString.cpp
  src/EbmlUnicodeString.cpp
  src/EbmlVoid.cpp
  test/test_infinite.cxx
  test/test_macros.cxx
Labels: api-break, abi-break

#226 switch to C++17
  CMakeLists.txt
Labels: enhancement, build-system

#229 Simplify calls to compute the HeadSize
  ebml/EbmlMaster.h
  src/EbmlElement.cpp
Labels: enhancement

#231 pass std::function by const ref
  ebml/EbmlBinary.h
  ebml/EbmlCrc32.h
  ebml/EbmlDate.h
  ebml/EbmlElement.h
  ebml/EbmlFloat.h
  ebml/EbmlMaster.h
  ebml/EbmlSInteger.h
  ebml/EbmlString.h
  ebml/EbmlUInteger.h
  ebml/EbmlUnicodeString.h
  ebml/EbmlVoid.h
  src/EbmlBinary.cpp
  src/EbmlCrc32.cpp
  src/EbmlDate.cpp
  src/EbmlElement.cpp
  src/EbmlFloat.cpp
  src/EbmlMaster.cpp
  src/EbmlSInteger.cpp
  src/EbmlString.cpp
  src/EbmlUInteger.cpp
  src/EbmlUnicodeString.cpp
  src/EbmlVoid.cpp
Labels: api-break, abi-break

#225 some clang-tidy fixes
  ebml/EbmlElement.h
  ebml/EbmlHead.h
  ebml/EbmlId.h
  src/EbmlBinary.cpp
  src/EbmlCrc32.cpp
  src/EbmlElement.cpp
  src/EbmlMaster.cpp
  src/EbmlSInteger.cpp
  src/EbmlString.cpp
  src/EbmlUInteger.cpp
  src/EbmlUnicodeString.cpp
  src/MemIOCallback.cpp
  src/SafeReadIOCallback.cpp
  src/StdIOCallback.cpp
Labels: enhancement
