Repository Matroska-Org/libebml, pull requests merged in 2024-02, with the labels that each got.

#235 string_view conversions
  ebml/EbmlUnicodeString.h
  src/EbmlUnicodeString.cpp
Labels: api-break, abi-break

#236 replace mIO with unique_ptr
  ebml/SafeReadIOCallback.h
  src/SafeReadIOCallback.cpp
Labels: api-break, abi-break

#241 generate a warning for alignement issues
  CMakeLists.txt
Labels: build-system

#260 disable most verbose warnings in MSVC in Dev Mode
  CMakeLists.txt
Labels: build-system

#250 Cleanup includes in public headers
  ebml/EbmlElement.h
  ebml/EbmlEndian.h
  ebml/EbmlId.h
  ebml/EbmlTypes.h
  ebml/IOCallback.h
  ebml/SafeReadIOCallback.h
  src/EbmlDate.cpp
  src/EbmlFloat.cpp
  src/EbmlUnicodeString.cpp
  src/MemIOCallback.cpp
  src/StdIOCallback.cpp
Labels: enhancement

#251 Simplify CRC32 writing
  src/EbmlCrc32.cpp
Labels: enhancement

#252 Use more standard exceptions and remove CRTError exception
  ebml/StdIOCallback.h
  src/EbmlBinary.cpp
  src/StdIOCallback.cpp
Labels: api-break, abi-break

#253 Fix sign conversion in MSVC byte swapping
  ebml/EbmlEndian.h
Labels: enhancement

#254 add missing filter checks in UpdateSize()
  ebml/EbmlDate.h
  src/EbmlBinary.cpp
  src/EbmlMaster.cpp
Labels: enhancement

#255 Rework EbmlVoid internals
  src/EbmlVoid.cpp
Labels: enhancement

#256 Make the size length Unsigned
  ebml/EbmlElement.h
  ebml/EbmlMaster.h
  src/EbmlElement.cpp
  src/EbmlMaster.cpp
Labels: api-break, abi-break

#257 fix MemIOCallback IOCallback write return type
  ebml/MemIOCallback.h
  src/MemIOCallback.cpp
Labels: api-break, abi-break

#259 use if constexpr for always constant test known at compilation time
  src/EbmlUnicodeString.cpp
Labels: enhancement

#262 drop CMake older than 3.5
  CMakeLists.txt
Labels: build-system

#263 Clean empty master context handling
  src/EbmlMaster.cpp
Labels: enhancement

#265 Use more constexpr return values/references
  ebml/EbmlElement.h
Labels: api-break, abi-break

#247 Reduce the number of methods and cleanup some macros
  ebml/EbmlDummy.h
  ebml/EbmlElement.h
  src/EbmlDummy.cpp
  src/EbmlElement.cpp
  src/EbmlMaster.cpp
  test/test_crc.cxx
  test/test_header.cxx
Labels: api-break, abi-break

#268 Fix DLL export a constexpr
  ebml/EbmlElement.h
Labels: api-break, abi-break

#271 remove linux-13 from the list of workflows
  README.md
Labels: documentation

#264 Turn main EBML macros into static inlines
  ebml/EbmlElement.h
Labels: api-break, abi-break
